import type { DealPricingPriceDetail, DealPricingRequest } from './data';

const cashPoolDetail = (): DealPricingPriceDetail => ({
  id: 'cash-pool-maintenance',
  feeItem: 'Cash Pool Monthly Maintenance',
  chargeService: 'FCY_DOMESTIC_CASH_POOL',
  tariffItemCode: 'TARIFF-002',
  pricingModel: 'FLAT',
  chargeBasis: 'Account',
  baselinePrice: 500,
  requestedPriceType: 'AMOUNT',
  requestedPrice: 420,
  currency: 'USD',
  mockAnnualVolume: 48,
});

const crossBorderDetail = (): DealPricingPriceDetail => ({
  id: 'cross-border-payment',
  feeItem: 'Cross-border Payment Fee',
  chargeService: 'CROSS_BORDER_PAYMENT',
  tariffItemCode: 'TARIFF-018',
  pricingModel: 'RATE',
  chargeBasis: 'Transaction Value',
  baselinePrice: 0.3,
  requestedPriceType: 'RATE',
  requestedPrice: 0.25,
  currency: 'USD',
  mockAnnualVolume: 2_400_000,
});

const tradeFinanceDetail = (): DealPricingPriceDetail => ({
  id: 'trade-finance-processing',
  feeItem: 'Trade Finance Processing Fee',
  chargeService: 'TRADE_FINANCE',
  tariffItemCode: 'PROMO-003',
  pricingModel: 'TIERED',
  chargeBasis: 'Transaction',
  baselinePrice: 1_000,
  requestedPriceType: 'DISCOUNT',
  requestedPrice: 10,
  currency: 'USD',
  mockAnnualVolume: 200,
});

export const initialDealPricingRequests: DealPricingRequest[] = [
  {
    id: 'DPR-2026-001',
    customerId: 'CUST-000128',
    customerName: 'ABC Global Holdings',
    customerSegment: 'Strategic Corporate',
    relationshipManager: 'Zhang San',
    requestType: 'NEW_AGREEMENT',
    requestReason: 'STRATEGIC_CUSTOMER',
    benchmarkSource: 'TARIFF',
    benchmarkPlan: 'Global Cash Management Tariff 2026',
    market: 'China',
    currency: 'USD',
    effectiveStartDate: '2026-09-01',
    ecrPricingRequested: true,
    ecrReason: 'Strategic relationship package',
    ecrReference: 'ECR-2026-0098',
    priceDetails: [cashPoolDetail(), crossBorderDetail()],
    simulation: {
      simulatedAt: '2026-08-19T10:30:00+08:00',
      baselineAnnualizedFee: 7_224,
      requestedAnnualizedFee: 6_521,
      estimatedRevenueImpact: -703,
      estimatedTotalRelationshipReturn: 2_309_297,
      requestedDiscountPercent: 9.7,
      thresholdStatus: 'WITHIN_THRESHOLD',
    },
    status: 'PENDING_APPROVAL',
    requestedBy: 'Li Wei',
    requestedAt: '2026-08-19T10:35:00+08:00',
  },
  {
    id: 'DPR-2026-002',
    customerId: 'CUST-000256',
    customerName: 'Pacific Trading Group',
    customerSegment: 'Large Corporate',
    relationshipManager: 'Chen Yu',
    requestType: 'RENEWAL',
    requestReason: 'COMPETITIVE_PRESSURE',
    benchmarkSource: 'PROMOTION',
    benchmarkPlan: 'APAC Trade Finance Renewal Promotion',
    market: 'Singapore',
    currency: 'USD',
    effectiveStartDate: '2026-10-01',
    effectiveEndDate: '2027-09-30',
    ecrPricingRequested: false,
    priceDetails: [tradeFinanceDetail()],
    simulation: {
      simulatedAt: '2026-08-18T14:20:00+08:00',
      baselineAnnualizedFee: 200_000,
      requestedAnnualizedFee: 180_000,
      estimatedRevenueImpact: -20_000,
      estimatedTotalRelationshipReturn: 1_040_000,
      requestedDiscountPercent: 10,
      thresholdStatus: 'REQUIRES_JUSTIFICATION',
    },
    status: 'SIMULATED',
    requestedBy: 'Chen Yu',
    requestedAt: '2026-08-18T14:25:00+08:00',
  },
  {
    id: 'DPR-2026-003',
    customerId: 'CUST-000384',
    customerName: 'Sakura Manufacturing Co.',
    customerSegment: 'Large Corporate',
    relationshipManager: 'Wang Fang',
    requestType: 'TEMPORARY_PROMOTION',
    requestReason: 'CROSS_SELL_OPPORTUNITY',
    benchmarkSource: 'TARIFF',
    benchmarkPlan: 'Japan Transaction Banking Tariff 2026',
    market: 'Japan',
    currency: 'USD',
    effectiveStartDate: '2026-09-01',
    effectiveEndDate: '2026-12-31',
    ecrPricingRequested: false,
    priceDetails: [cashPoolDetail()],
    status: 'DRAFT',
    requestedBy: 'Wang Fang',
    requestedAt: '2026-08-17T09:10:00+08:00',
  },
];

export const clonePriceDetails = (details: DealPricingPriceDetail[]) =>
  details.map((detail) => ({ ...detail }));

export const priceDetailOptions = () => [
  cashPoolDetail(),
  crossBorderDetail(),
  tradeFinanceDetail(),
];
